apps/productsapp/urls.py
from django.conf.urls import url
from . import views

app_name='products'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.new, name='new'),
    url(r'^create$', views.create, name='create'),
    url(r'^show/(?P<id>\d+)$', views.show, name='show'),
    url(r'^edit/(?P<id>\d+)$', views.edit, name='edit'),
    url(r'^update/(?P<id>\d+)$', views.update, name='update'),
    url(r'^destroy/(?P<id>\d+)$', views.delete, name='delete'),
]





# index: Display all products
# show: Display a particular product
# new: Display a form to create a new product
# edit: Display a form to update a product
# create: Process information to create a new product
# update: Process information from the edit form and update the particular product
# destroy: Remove a product

products/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.productsapp.urls', namespace='products_app')),
]

apps/productsapp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class ProductManager(models.Manager):
    def create_product(self, data):

        create = Product.objects.create(
        name = data['name'],
        description = data['description'],
        price = data['price'],
        )
        print create, "<---"
        return (True, create)

    def edit_product(self, data):
        edit= Product.objects.get(id = data['id'])
        edit.name,edit.description,edit.price = (data['name'],data['description'], data['price'])
        edit.save()
        return (edit)
        # edit.name.add(data['name'])
        # edit.description=data['description']
        # edit.price=data['price']
        # edit.save()


        # edit[0].name = data['name']
        # edit[0].description = data['description']
        # edit[0].price = data['price']
        # edit[0].save()




class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=15, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ProductManager()

    def __unicode__(self):
        return unicode(self.id)+" "+ self.name+" "+self.description+" "+unicode(self.price)

apps/productsapp/views.py
from django.shortcuts import render, redirect

from .models import Product
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    context={
        'products': Product.objects.all()
    }
    return render(request, 'productsapp/index.html', context)

def new(request):

    return render(request, 'productsapp/add.html')

def create(request):
    process = Product.objects.create_product(request.POST)

    if process == True:
        print process, "<----"

    return redirect('products:index')

def show(request, id):
    print id
    context={
        'products': Product.objects.filter(id=id)
    }
    return render(request, 'productsapp/show.html', context)

def edit(request, id):
    context={
        'products': Product.objects.filter(id=id)
    }
    return render(request, 'productsapp/edit.html', context)

def update(request, id):
    process= Product.objects.edit_product(request.POST)

    return redirect('products:index')

def delete(request, id):
    delete = Product.objects.get(id=id)
    delete.delete()

    return redirect('products:index')


# def show_product(request, id):
#     product_id= Product.objects.get(id=id)
#
#     return redirect(revers('products:show', id=id))






# index: Display all products
# show: Display a particular product
# new: Display a form to create a new product
# edit: Display a form to update a product
# create: Process information to create a new product
# update: Process information from the edit form and update the particular product
# destroy: Remove a product

apps/productsapp/templates/productsapp/add.html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <title>Add ProductManager</title>
      {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'productsapp/css/bootstrap.css' %}">
   </head>
   <body>
      <div class="container">
         <div class="row">
            <h3>Add a Product</h3>
            <hr>
            <div class="col-md-2 form-group">
               <form class="" action="{% url 'products:create' %}" method="post">
                   {% csrf_token %}
                  <label for="name">Name:</label><input type="text" name="name" value="">
                  <label for="description">Description:</label><input type="text" name="description" value="">
                  <label for="price">Price:</label><input type="text" name="price" value="">
                  <button type="submit" name="submit">Create</button>
               </form>
               <a href="{% url 'products:index' %}">Go Back</a>
            </div>
         </div>
      </div>
   </body>
</html>

apps/productsapp/templates/productsapp/edit.html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <title>Edit products</title>
      {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'productsapp/css/bootstrap.css' %}">
   </head>
   <body>
      <div class="row">
         <div class="col-md-2 pull-md-3">
            {% for product in products %}
            <form class="form-group" action="{% url 'products:update3' product.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{product.id}}">
               <label for="name">Name:</label><input type="text" name="name" value="{{product.name}}">
               <label for="description">Description:</label><input type="text" name="description" value="{{product.description}}">
               <label for="price">Price:</label><input type="text" name="price" value=" {{product.price}}">
               <button type="submit" name="submit">Update</button>
            </form>
            <br>
            <br>
            <a href="{% url 'products:show' product.id %}">Show</a> |
            <a href="{% url 'products:index' %}"> Go Back</a>
            {% endfor %}
         </div>
      </div>
   </body>
</html>

apps/productsapp/templates/productsapp/index.html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <title>Products page</title>
      {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'productsapp/css/bootstrap.css' %}">
   </head>
   <body>
      <div class="container">
         <div class="row">
            <div class="col">
               <h3>Products</h3>
               <hr>
            </div>
         </div>
         <div class="row">
            <div class="col">
               <table class= "table table-hover">
                  <thead>
                     <th>Name</th>
                     <th>Description</th>
                     <th>Price</th>
                     <th>Action</th>
                  </thead>
                  <tr>
                     {% for product in products %}
                     <td>{{product.name}}</td>
                     <td>{{product.description}}</td>
                     <td>$ {{product.price}}</td>
                     <td>
                        <a href="{% url 'products:show' product.id %}">Show</a> |
                        <a href="{% url 'products:edit' product.id %}">Edit</a> |
                        <a href="{% url 'products:delete' product.id %}"><button type="button" name="button">Remove</button></a>
                     </td>
                  </tr>
                  {% endfor %}
               </table>
            </div>
         </div>
         <br>
         <br>
         <a href="{% url 'products_app:new' %}">Add A New Product</a>
      </div>
   </body>
</html>

apps/productsapp/templates/productsapp/show.html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <title>Show</title>
      {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'productsapp/css/bootstrap.css' %}">
   </head>
   <body>
      <div class="container">
         <div class="row">
            <div class="col">
               {% for product in products %}
               <h3>Id: {{product.id}}</h3>
               <h3>Product: {{product.name}}</h3>
               <h4>Description: {{product.description}}</h4>
               <h4>Price:$ {{product.price}}</h4>
               <br>
               <br>
               <a href="{% url 'products:edit' product.id %}">Edit</a> |
               <a href="{% url 'products:index' %}">Go Back</a>
               {% endfor %}
            </div>
         </div>
      </div>
   </body>
</html>